App\Entity\Competence:
  attributes:
    id:
      groups: [ 'competence_read','grpecompetence_read' ]
    libelle:
      groups: [ 'competence_read','grpecompetence_read','competence_write' ]
    groupecompetences:
      groups: [ 'competence_read' ]
    niveaux:
      groups: [ 'competence_write' ]