App\Entity\Competence:
  attributes:
    id:
      groups: [ 'competence:read','grpecompetence_read' ]
    libelle:
      groups: [ 'competence:read','grpecompetence_read' ]
    groupecompetences:
      groups: [ 'competence:read' ]
    niveaux:
      groups: [ 'competence:read' ]