App\Entity\Competence:
  attributes:
    id:
      groups: [ 'competence:read','grpecompetence_read','referentiel_in_promo:read','grpeCompetence:write','brief_in_group:read' ]
    libelle:
      groups: [ 'competence:read','grpecompetence_read','referentiel_in_promo:read','grpeCompetence:write','competence:write','brief_in_group:read' ]
    groupecompetences:
      groups: [ 'competence:read','competence:write' ]
    niveaux:
      groups: [ 'competence:read','competence:write' ]