App\Entity\Niveau:
  attributes:
    id:
      groups: ['niveau:read','competence:read']
    libelle:
      groups: [ 'competence:read', 'niveau:read' ]
    critereEvaluation:
      groups: [ 'competence:read','niveau:read' ]
    groupeAction:
      groups: [ 'competence:read','niveau:read' ]
