App\Entity\Ressource:
  attributes:
    id:
      groups: ['brief:read','brief:write','brief_in_group:read']
    title:
      groups: ['brief:read','brief:write','brief_in_group:read']
    url:
      groups: ['brief:read','brief:write','brief_in_group:read']
    pieceJointe:
      groups: ['brief:read','brief:write','brief_in_group:read']