App\Entity\User:
  attributes:
    id:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read', 'waiting_student:read', 'get_students_in_grpe_promo:read' ]
    firstname:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read', 'waiting_student:read', 'get_students_in_grpe_promo:read' ]
    lastname:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read', 'waiting_student:read', 'get_students_in_grpe_promo:read' ]
    email:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read', 'waiting_student:read', 'get_students_in_grpe_promo:read' ]
    username:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read', 'waiting_student:read', 'get_students_in_grpe_promo:read' ]
    isDeleted:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read' ]
    avatar:
      groups: [ 'users_with_this_profil','user_read','promo_read', 'grpe_principal_in_promo:read', 'waiting_student:read', 'get_students_in_grpe_promo:read' ]
    isWaiting:
      groups: [ 'waiting_student:read', 'get_students_in_grpe_promo:read' ]