App\Entity\GroupeTag:
  properties:
    libelle:
      - NotBlank:
          message: This field is required
          groups: [ 'brief_validation' ]
    tags:
      - Count:
          min: 1
          minMessage: This groupetag must be at least associated with {{ limit }} Tag
      - Valid: ~
