App\Entity\Tag:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: libelle
  properties:
    libelle:
      - NotBlank:
          message: This field is required
          groups: [ 'brief_validation' ]
    groupeTags:
      - Count:
          min: 1
          minMessage: This tag must be at least in {{ limit }} groupeTag
      - Valid:
          groups: [ 'brief_validation' ]
