App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [email,username]
  properties:
    firstname:
      - NotBlank:
          message: This field is required
      - Length:
          min: 4
          minMessage: The min length is 4 characters
    lastname:
      - NotBlank:
          message: This field is required
      - Length:
          min: 4
          minMessage: The min length is 4 characters
    username:
      - NotBlank:
          message: This field is required
      - Length:
          min: 4
          minMessage: The min length is 4 characters
    password:
      - NotBlank:
          message: This field is required
      - Length:
          min: 6
          minMessage: The min length is 6 characters
    email:
      - NotBlank:
          message: This field is required
      - Email:
          message: This email "{{ value }}" is'nt valid
