App\Entity\Promo:
  attributes:
    route_prefix: /admin
    normalization_context:
      groups: [ 'promo_read' ]
    deserialize: false
    security: is_granted('ROLE_FORMATEUR')
    security_message: You're unauthorized to access this resource.
  properties:
    referentiel:
      subresource:
        resourceClass: App\Entity\Referentiel
        security: is_granted('ROLE_CM')
    groupes:
      subresource:
        resourceClass: App\Entity\Groupe
  collectionOperations:
    get_promos:
      method: GET
      path: /promos
      security: is_granted('ROLE_CM')
    add_promo:
      method: POST
      path: /promos
      controller: App\Controller\PromoController::addPromo
    get_promo_grpe_principals:
      method: GET
      path: /promos/principal
      security: is_granted('ROLE_CM')
    get_waiting_students_in_promos:
      method: GET
      path: /promos/apprenants/attente
  itemOperations:
    get_promo:
      method: GET
      path: /promos/{id}
      requirements:
        id: \d+
      security: is_granted('ROLE_CM')
    set_promo:
      method: PUT
      path: /promos/{id}
      requirements:
        id: \d+
    delete_promo:
      method: DELETE
      path: /promos/{id}
      requirements:
        id: \d+
      security: is_granted('ROLE_ADMIN')
    get_promo_grpe_principal:
      method: GET
      path: /promos/{id}/principal
      requirements:
        id: \d+
      security: is_granted('ROLE_CM')
    get_waiting_student_in_promo:
      method: GET
      path: /promos/{id}/apprenants/attente
      requirements:
        id: \d+
      security: is_granted('ROLE_CM')
    get_student_in_grpe_promo:
      method: GET
      path: /promos/{idPromo}/groupes/{idGrpe}/apprenants
      requirements:
        idPromo: \d+
        idGrpe: \d+
      security: is_granted('ROLE_CM')
    get_teachers_in_grpe:
      method: GET
      path: /promos/{id}/formateurs
      requirements:
        id: \d+
      security: is_granted('ROLE_CM')
    set_students_in_promo:
      method: PUT
      path: /promos/{id}/apprenants
      requirements:
        id: \d+
    set_teacher_in_promo:
      method: PUT
      path: /promos/{id}/formateurs
      requirements:
        id: \d+
    set_grpe_status_in_promo:
      method: PUT
      path: /promos/{idPromo}/groupes/{idGrpe}
      requirements:
        idPromo: \d+
        idGrpe: \d+
